const editor = document.querySelector('#editor');
const state = { title: 'Untitled document', zoom: 1, dirty: false, theme: localStorage.getItem('nexa-theme') || 'light' };
const $ = (s) => document.querySelector(s);

function markDirty() { state.dirty = true; $('#saved-state').textContent = 'Unsaved changes'; updateCounts(); updateHeadings(); }
function exec(command, value = null) { editor.focus(); document.execCommand(command, false, value); markDirty(); }
function updateCounts() { const text = editor.innerText.trim(); const words = text ? text.split(/\s+/).length : 0; $('#word-count').textContent = `${words.toLocaleString()} words`; $('#char-count').textContent = `${text.length.toLocaleString()} characters`; $('#page-count').textContent = `Page ${Math.max(1, Math.ceil(text.length / 2200))} of ${Math.max(1, Math.ceil(text.length / 2200))}`; }
function updateHeadings() { const target = $('#headings'); const headings = [...editor.querySelectorAll('h1,h2,h3')]; target.innerHTML = headings.length ? '' : '<p class="muted">Headings will appear here</p>'; headings.forEach((heading, index) => { heading.id = `heading-${index}`; const button = document.createElement('button'); button.textContent = heading.textContent || 'Untitled heading'; button.style.paddingLeft = `${8 + (Number(heading.tagName[1]) - 1) * 12}px`; button.onclick = () => heading.scrollIntoView({ behavior: 'smooth', block: 'center' }); target.append(button); }); }
function saveDocument() { const data = { version: 1, title: state.title, html: editor.innerHTML, savedAt: new Date().toISOString() }; localStorage.setItem('nexa-autosave', JSON.stringify(data)); const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${state.title || 'Untitled document'}.nexa`; link.click(); URL.revokeObjectURL(link.href); state.dirty = false; $('#saved-state').textContent = 'Saved'; }
function exportText() { const blob = new Blob([editor.innerText], { type: 'text/plain;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${state.title || 'Untitled document'}.txt`; link.click(); URL.revokeObjectURL(link.href); }
function openDocument(file) { const reader = new FileReader(); reader.onload = () => { try { if (file.name.endsWith('.nexa')) { const data = JSON.parse(reader.result); state.title = data.title || 'Untitled document'; editor.innerHTML = data.html || '<p><br></p>'; } else if (file.name.match(/\.html?$/i)) editor.innerHTML = reader.result; else editor.innerHTML = `<p>${escapeHtml(reader.result).replaceAll('\n','</p><p>')}</p>`; $('#document-title').textContent = state.title; state.dirty = false; $('#saved-state').textContent = 'Saved'; updateCounts(); updateHeadings(); } catch { alert('Nexa could not open this file. The document may be invalid or corrupted.'); } }; reader.readAsText(file); }
function escapeHtml(value) { const div = document.createElement('div'); div.textContent = value; return div.innerHTML; }
function insertTable() { const rows = Number(prompt('Number of rows', '3')); const cols = Number(prompt('Number of columns', '3')); if (!rows || !cols || rows > 20 || cols > 12) return; let html = '<table><tbody>'; for (let r=0;r<rows;r++) { html += '<tr>'; for (let c=0;c<cols;c++) html += '<td><br></td>'; html += '</tr>'; } editor.focus(); document.execCommand('insertHTML', false, html + '</tbody></table><p><br></p>'); markDirty(); }
function insertLink() { const url = prompt('Enter a website or email address'); if (url) exec('createLink', /^https?:\/\//.test(url) || url.startsWith('mailto:') ? url : `https://${url}`); }
function applyStyle(tag) { exec('formatBlock', tag === 'p' ? 'p' : tag); }
function showMenu(name, anchor) { const menu = $('#menu-popover'); const items = { file:[['New document','new'],['Open…','open','Ctrl+O'],['Save document','save','Ctrl+S'],['Export text…','export'],['Print','print','Ctrl+P']], edit:[['Undo','undo','Ctrl+Z'],['Redo','redo','Ctrl+Y'],['Find','find','Ctrl+F'],['Replace','replace','Ctrl+H']], view:[['Navigation pane','sidebar'],['Zoom in','zoomIn'],['Zoom out','zoomOut'],['Reset zoom','zoomReset']], insert:[['Page break','pagebreak'],['Table…','table'],['Image…','image'],['Hyperlink…','link']], format:[['Bold','bold','Ctrl+B'],['Italic','italic','Ctrl+I'],['Underline','underline','Ctrl+U'],['Clear formatting','clear']], tools:[['Word count','count']] }; menu.innerHTML = (items[name] || []).map(([label, action, key]) => `<button data-action="${action}">${label}<kbd>${key || ''}</kbd></button>`).join(''); menu.hidden = false; const rect = anchor.getBoundingClientRect(); menu.style.left = `${rect.left}px`; menu.style.top = `${rect.bottom + 4}px`; }
function action(action) { const actions = { new:()=>{ if(state.dirty && !confirm('Discard unsaved changes?')) return; state.title='Untitled document'; editor.innerHTML='<h1>Untitled document</h1><p><br></p>'; }, open:()=>$('#open-input').click(), save:saveDocument, export:exportText, print:()=>window.print(), undo:()=>exec('undo'), redo:()=>exec('redo'), find:()=>findText(), replace:()=>replaceText(), sidebar:()=>$('#sidebar').toggleAttribute('hidden'), zoomIn:()=>setZoom(state.zoom + .1), zoomOut:()=>setZoom(state.zoom - .1), zoomReset:()=>setZoom(1), pagebreak:()=>exec('insertHTML','<div style="break-after:page;height:1px"></div>'), table:insertTable, image:()=>$('#image-input').click(), link:insertLink, bold:()=>exec('bold'), italic:()=>exec('italic'), underline:()=>exec('underline'), clear:()=>exec('removeFormat'), count:()=>alert(`${$('#word-count').textContent}\n${$('#char-count').textContent}`) }; if(actions[action]) actions[action](); $('#menu-popover').hidden=true; updateCounts(); updateHeadings(); }
function findText() { const query = prompt('Find text'); if (!query) return; const found = window.find(query); if (!found) alert('No matches found.'); }
function replaceText() { const from=prompt('Find text'); if(!from)return; const to=prompt('Replace with',''); if(to===null)return; editor.innerHTML=editor.innerHTML.split(from).join(escapeHtml(to)); markDirty(); }
function setZoom(value) { state.zoom=Math.min(1.5,Math.max(.6,value)); $('.page').style.transform=`scale(${state.zoom})`; $('#zoom-level').textContent=`${Math.round(state.zoom*100)}%`; }

$$('[data-command]').forEach(b=>b.onclick=()=>exec(b.dataset.command)); function $$(s){return [...document.querySelectorAll(s)]}
$$('[data-menu]').forEach(b=>b.onclick=()=>showMenu(b.dataset.menu,b)); $('#menu-popover').onclick=e=>{const b=e.target.closest('[data-action]');if(b)action(b.dataset.action)};
$('#style-select').onchange=e=>applyStyle(e.target.value); $('#font-select').onchange=e=>exec('fontName',e.target.value); $('#size-select').onchange=e=>exec('fontSize',Math.min(7,Math.max(1,Math.round(Number(e.target.value)/3))));
$('#insert-table').onclick=insertTable; $('#insert-link').onclick=insertLink; $('#insert-image').onclick=()=>$('#image-input').click(); $('#image-input').onchange=e=>{const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{exec('insertImage',reader.result);markDirty()};reader.readAsDataURL(f)}; $('#open-input').onchange=e=>{if(e.target.files[0])openDocument(e.target.files[0])};
$('#undo').onclick=()=>exec('undo'); $('#redo').onclick=()=>exec('redo'); $('#zoom-in').onclick=()=>setZoom(state.zoom+.1); $('#zoom-out').onclick=()=>setZoom(state.zoom-.1); $('#close-sidebar').onclick=()=>$('#sidebar').setAttribute('hidden',''); $('#theme-toggle').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';document.body.classList.toggle('dark',state.theme==='dark');localStorage.setItem('nexa-theme',state.theme)}; $('#help-button').onclick=()=>alert('Shortcuts: Ctrl+N new, Ctrl+O open, Ctrl+S save, Ctrl+F find, Ctrl+H replace, Ctrl+B bold, Ctrl+I italic, Ctrl+Z undo.');
editor.addEventListener('input',markDirty); editor.addEventListener('keyup',updateCounts); document.addEventListener('click',e=>{if(!e.target.closest('.menu-bar')&&!e.target.closest('.menu-popover'))$('#menu-popover').hidden=true}); document.addEventListener('keydown',e=>{if(!(e.ctrlKey||e.metaKey))return; const key=e.key.toLowerCase(); if(key==='s'){e.preventDefault();saveDocument()} if(key==='o'){e.preventDefault();$('#open-input').click()} if(key==='n'){e.preventDefault();action('new')} if(key==='f'){e.preventDefault();findText()} if(key==='h'){e.preventDefault();replaceText()} if(key==='p'){e.preventDefault();window.print()}}); window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue=''}});
document.body.classList.toggle('dark',state.theme==='dark'); updateCounts(); updateHeadings();
